// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Main.JSON_Classes.LootFarm;
//
//    var lootBotDotaInv = LootBotDotaInv.FromJson(jsonString);

namespace Main.JSON_Classes.LootFarm
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class LootBotDotaInv
    {
        [JsonProperty("result")]
        public Dictionary<string, Result> Result { get; set; }
    }

    public partial class Result
    {
        /// <summary>
        /// Bots items : key = bot, value = item
        /// </summary>
        [JsonProperty("u")]
        public Dictionary<string, List<U>> ItemsOnBots { get; set; }
    }

    public partial class LootBotDotaInv
    {
        public static LootBotDotaInv FromJson(string json) => JsonConvert.DeserializeObject<LootBotDotaInv>(json, Main.JSON_Classes.LootFarm.Converter.Settings);
    }

    public static class SerializeDotaMoney
    {
        public static string ToJson(this LootBotDotaInv self) => JsonConvert.SerializeObject(self, Main.JSON_Classes.LootFarm.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
