// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Main.JSON_CLASSES;
//
//    var tradeItH1Z1 = TradeItH1Z1.FromJson(jsonString);

namespace Main.JSON_Classes.TradeIt
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TradeItH1Z1 : MainTradeIt
    {
        [JsonProperty("433850")]
        public override GameCode GameCode { get; set; }
    }

    public static class SerializeTradeItH1Z1
    {
        public static string ToJson(this List<TradeItH1Z1> self) => JsonConvert.SerializeObject(self, Main.Support.Converter.Settings);
    }
    public partial class TradeItH1Z1
    {
        public static List<TradeItH1Z1> FromJson(string json) => JsonConvert.DeserializeObject<List<TradeItH1Z1>>(json, Main.Support.Converter.Settings);
    }
}
