// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Main;
//
//    var lootItems = LootItems.FromJson(jsonString);

namespace Main
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class LootItems
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("price")]
        public long Price { get; set; }

        [JsonProperty("have")]
        public long Have { get; set; }

        [JsonProperty("max")]
        public long Max { get; set; }

        [JsonProperty("rate")]
        public long Rate { get; set; }

    }

    public partial class LootItems
    {
        public static List<LootItems> FromJson(string json) => JsonConvert.DeserializeObject<List<LootItems>>(json, Main.Converter.Settings);
    }

    public static class SerializeLoot
    {
        public static string ToJson(this List<LootItems> self) => JsonConvert.SerializeObject(self, Main.Converter.Settings);
    }

}
