// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Main.JSON_Classes.Swap;
//
//    var swapBalance = SwapBalance.FromJson(jsonString);

namespace Main.JSON_Classes.Swap
{
    using Main.Support;
    using Newtonsoft.Json;

    public partial class SwapBalance
    {
        [JsonProperty("success")]
        public bool Success { get; set; }

        [JsonProperty("result")]
        public long Result { get; set; }
    }

    public partial class SwapBalance
    {
        public static SwapBalance FromJson(string json) => JsonConvert.DeserializeObject<SwapBalance>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this SwapBalance self) => JsonConvert.SerializeObject(self,Converter.Settings);
    }
}
